### ISSUE TITLE
Failed to load plugin FanControl.DellPlugin.dll

### ISSUE THREAD

**Issue by escher54** [Rem0o/FanControl.DellPlugin#6]
I keep getting these errors and the Dell Plugin will not load for the Fan Control:

> 5/13/2022 4:51:09 PM: Failed to load plugin FanControl.DellPlugin.dll.
5/13/2022 4:51:09 PM: System.IO.FileLoadException: Could not load file or assembly 'file:///D:\Program Files\FanControl\Plugins\FanControl.DellPlugin.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///D:\Program Files\FanControl\Plugins\FanControl.DellPlugin.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at FanControl.Domain.PluginService.LoadAssembly(FileInfo dll)

**Comment by escher54** [comment]
i found a previous issue reported, but the user closed it
https://github.com/Rem0o/FanControl.DellPlugin/issues/2

After reading this i checked the bzh_dell_smm_io_x64.sys file and saw it was blocked and had to unblock it. 

Is there something that can be done to fix this or just include that in the steps to unblock it?

**Comment by Rem0o** [comment]
@escher54  I should just probably mention to unlock them from the readme.

**Comment by escher54** [comment]
@Rem0o agree a simple solution like that would be good for future people attempting to use it.
