### ISSUE TITLE
Plugin cannot open 'bzh_[...].sys' despite having full access to it

### ISSUE THREAD

**Issue by dfault-user** [Rem0o/FanControl.DellPlugin#9]
`12/24/2022 01:16:34: Dell plugin could not initialize. See the error log for more details.
12/24/2022 01:18:01: System.UnauthorizedAccessException: Access to the path 'D:\FC1\bzh_dell_smm_io_x64.sys' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at FanControl.DellPlugin.DellPlugin.DeleteExisting()
   at FanControl.DellPlugin.DellPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
12/24/2022 01:18:01: Dell plugin could not initialize. See the error log for more details.`
I'm genuinely unsure on what I do wrong with this plugin every time I use it, because it's happened across three separate machines.

**Comment by otherside1** [comment]
Do you copy all the files or just FanControl.DellPlugin.dll

**Comment by dfault-user** [comment]
I copied all of the files as needed. The plugin copies bzh_[...].sys to the
program folder.
Thanks,
Brandan Delafuente
***@***.***

**Comment by Rem0o** [comment]
Did you do the registry edit then rebooted? See README.
